version: "3"

services:
  stacked-postgres:
    image: postgres:11.3-alpine
    container_name: solardev-postgres
    environment:
      - POSTGRES_DATABASE=solardev
      - POSTGRES_USER=solardev
      - POSTGRES_PASSWORD=solar123
    ports:
      - 5432:5432
    volumes:
      # copy startup script to /docker-entrypoint-initdb.d directory
      # used for initiating database
      - ./create_db.sh:/docker-entrypoint-initdb.d/create_db.sh

      # persist data
      - postgres-data:/var/lib/postgres/data
    restart: on-failure

volumes:
  postgres-data:
